name: Update Zag Dependencies

on: workflow_dispatch

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Upgrade Dependencies
        run: yarn upgrade --scope @zag-js --latest

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: Update Zag Dependencies
          delete-branch: true
          branch: chore/update-deps
